server:
  port: 8288

# 配置日志信息
logging:
  level:
    root: INFO
    com.github.bg.admin.core: DEBUG

spring:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 20
        min-idle: 0
      timeout: 2000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vcm?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

swagger:
  title: 用户权限架构的接口测试中心
  description: 用户权限架构的接口测试专用API文档
  base-package: com.github.bg.admin.core.controller
  contact:
    name: 林泽锋
    email: 282245889@qq.com

auth:
  # authToken的过期时间
  authTokenExpire: 3600
  # refreshToken过期时间
  refreshTokenExpire: 7200
  # 放行的权限列表，采用小写的冒号分隔
  releaseUrl: /user/refreshToken
  # false表示用户单点登陆,true表示用户多点登录
  singleLanding: false

# 文件上传的地址
file:
  upload:
    path: D:/static/merJoinResource/


