spring:
  profiles:
    active: dev

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml,classpath:chat/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true